CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,role TEXT NOT NULL CHECK(role IN ('CEO','DIRECTING_MANAGER','ASSISTANT_MANAGER','DEPARTMENT_HEAD','EMPLOYEE')),department_id BIGINT,branch_id BIGINT,status TEXT NOT NULL DEFAULT 'PENDING',password_hash TEXT NOT NULL,must_change_password BOOLEAN DEFAULT true,mfa_secret TEXT,mfa_enabled BOOLEAN DEFAULT false,mfa_skipped BOOLEAN DEFAULT false,failed_logins INT DEFAULT 0,locked_until TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS branches(id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS departments(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,branch_id BIGINT REFERENCES branches(id),head_user_id BIGINT,active BOOLEAN DEFAULT TRUE,UNIQUE(name,branch_id));
CREATE TABLE IF NOT EXISTS sessions(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),token_hash TEXT UNIQUE NOT NULL,mfa_verified BOOLEAN DEFAULT false,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS audit(id BIGSERIAL PRIMARY KEY,actor_id BIGINT,event TEXT NOT NULL,object_type TEXT,object_id TEXT,detail JSONB DEFAULT '{}',ip TEXT,at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),title TEXT NOT NULL,message TEXT,link TEXT,read BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS policies(id BIGSERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,title TEXT NOT NULL,category TEXT DEFAULT 'Security',current_version_id BIGINT,created_by BIGINT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS policy_versions(id BIGSERIAL PRIMARY KEY,policy_id BIGINT REFERENCES policies(id),version INT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'DRAFT',mandatory BOOLEAN DEFAULT TRUE,approved_by BIGINT,created_by BIGINT,assigned_roles TEXT[] DEFAULT '{}',ack_deadline TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),published_at TIMESTAMPTZ,UNIQUE(policy_id,version));
CREATE TABLE IF NOT EXISTS acknowledgments(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),version_id BIGINT REFERENCES policy_versions(id),at TIMESTAMPTZ DEFAULT now(),UNIQUE(user_id,version_id));
CREATE TABLE IF NOT EXISTS courses(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,description TEXT DEFAULT '',category TEXT DEFAULT 'Security Awareness',level TEXT DEFAULT 'BEGINNER',source TEXT DEFAULT 'COMPANY',cover_url TEXT,completion_type TEXT DEFAULT 'QUIZ',certificate BOOLEAN DEFAULT TRUE,points INT NOT NULL DEFAULT 20 CHECK(points BETWEEN 0 AND 1000),pass_mark INT DEFAULT 70 CHECK(pass_mark BETWEEN 0 AND 100),max_attempts INT DEFAULT 3,status TEXT DEFAULT 'DRAFT',created_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS resources(id BIGSERIAL PRIMARY KEY,course_id BIGINT REFERENCES courses(id),title TEXT NOT NULL,kind TEXT NOT NULL,locator TEXT NOT NULL,download_allowed BOOLEAN DEFAULT false,sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS questions(id BIGSERIAL PRIMARY KEY,course_id BIGINT REFERENCES courses(id),prompt TEXT NOT NULL,options JSONB NOT NULL,correct JSONB NOT NULL,marks INT DEFAULT 1);
CREATE TABLE IF NOT EXISTS assignments(id BIGSERIAL PRIMARY KEY,course_id BIGINT REFERENCES courses(id),user_id BIGINT REFERENCES users(id),due_at TIMESTAMPTZ NOT NULL,status TEXT DEFAULT 'ASSIGNED',completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(course_id,user_id));
CREATE TABLE IF NOT EXISTS attempts(id BIGSERIAL PRIMARY KEY,assignment_id BIGINT REFERENCES assignments(id),score NUMERIC(6,2),passed BOOLEAN,answers JSONB,at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS evidence(id BIGSERIAL PRIMARY KEY,assignment_id BIGINT REFERENCES assignments(id),user_id BIGINT REFERENCES users(id),file_path TEXT,comment TEXT,status TEXT DEFAULT 'PENDING',reviewed_by BIGINT,review_comment TEXT,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS extensions(id BIGSERIAL PRIMARY KEY,assignment_id BIGINT REFERENCES assignments(id),requester_id BIGINT REFERENCES users(id),requested_due TIMESTAMPTZ,reason TEXT,status TEXT DEFAULT 'PENDING',reviewer_id BIGINT,decision TEXT,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS points(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),assignment_id BIGINT UNIQUE REFERENCES assignments(id),amount INT NOT NULL,awarded_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS campaigns(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,landing_message TEXT DEFAULT 'This was a security-awareness simulation.',status TEXT DEFAULT 'DRAFT',target_department BIGINT,created_by BIGINT,scheduled_at TIMESTAMPTZ,launched_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS campaign_targets(id BIGSERIAL PRIMARY KEY,campaign_id BIGINT REFERENCES campaigns(id),user_id BIGINT REFERENCES users(id),tracking_token TEXT UNIQUE,clicked_at TIMESTAMPTZ,sent_at TIMESTAMPTZ,UNIQUE(campaign_id,user_id));
CREATE INDEX IF NOT EXISTS idx_audit_at ON audit(at DESC);CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS idx_assign_user ON assignments(user_id);CREATE INDEX IF NOT EXISTS idx_points_user ON points(user_id,awarded_at);

-- Preserve active MFA while a replacement authenticator is being verified.
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_pending_secret TEXT;
